-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 23:04:43 2017
-- Model: Academia Digital    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academiadigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academiadigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academiadigital` DEFAULT CHARACTER SET utf8 ;
USE `academiadigital` ;

-- -----------------------------------------------------
-- Table `academiadigital`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadigital`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(21) NOT NULL,
  `last_name` VARCHAR(31) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadigital`.`muscle_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadigital`.`muscle_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(21) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadigital`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadigital`.`exercise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(51) NOT NULL,
  `muscle_group_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `muscle_group_fk_idx` (`muscle_group_id` ASC),
  CONSTRAINT `muscle_group_fk`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `academiadigital`.`muscle_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadigital`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadigital`.`training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` CHAR(1) NOT NULL,
  `customer_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `exercise_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `customer_id_fk_idx` (`customer_id` ASC),
  CONSTRAINT `customer_id_fk`
    FOREIGN KEY (`customer_id`)
    REFERENCES `academiadigital`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academiadigital`.`training_exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academiadigital`.`training_exercise` (
  `training_id` INT NOT NULL,
  `exercise_id` INT NOT NULL,
  INDEX `exercise_id_fk_idx` (`exercise_id` ASC),
  INDEX `training_id_fk_idx` (`training_id` ASC),
  CONSTRAINT `training_id_fk`
    FOREIGN KEY (`training_id`)
    REFERENCES `academiadigital`.`training` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exercise_id_fk`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `academiadigital`.`exercise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
